# Generated by Django 5.2.7 on 2026-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('venues', '0011_alter_venue_options_alter_venue_index_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venueconstraint',
            index=models.Index(fields=['subject_content_type', 'subject_id'], name='venue_constraint_subject_idx'),
        ),
    ]
