# Generated by Django 5.2.7 on 2026-03-06 11:29

import django.db.models.deletion
import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_add_workspace_fields'),
        ('tournaments', '0039_enforce_organization_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainSlugReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True, validators=[tournaments.models.validate_dns_safe_slug], verbose_name='slug')),
                ('tenant_type', models.CharField(choices=[('tournament', 'Tournament'), ('organization', 'Organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_reservation', to='organizations.organization')),
                ('tournament', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slug_reservation', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'subdomain slug reservation',
                'verbose_name_plural': 'subdomain slug reservations',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('organization__isnull', True), ('tenant_type', 'tournament'), ('tournament__isnull', False)), models.Q(('organization__isnull', False), ('tenant_type', 'organization'), ('tournament__isnull', True)), _connector='OR'), name='slug_reservation_exactly_one_target')],
            },
        ),
    ]
