# Generated by Django 5.2.7 on 2026-02-16 17:58

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activesession',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AlterModelOptions(
            name='dailystats',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily stats'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='activesession',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activesession',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='ballots_submitted',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='new_users',
        ),
        migrations.RemoveField(
            model_name='dailystats',
            name='page_views',
        ),
        migrations.AddField(
            model_name='dailystats',
            name='active_tournaments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='ballots_entered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='debates_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='new_signups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='top_countries',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='top_pages',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailystats',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pageview',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pageview',
            name='full_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='current_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activesession',
            name='session_key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='tournaments_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailystats',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        # Drop the old bigint PK and recreate as UUID
        migrations.RunSQL(
            sql=[
                'ALTER TABLE analytics_pageview DROP CONSTRAINT IF EXISTS analytics_pageview_pkey;',
                'ALTER TABLE analytics_pageview DROP COLUMN id;',
                'ALTER TABLE analytics_pageview ADD COLUMN id uuid DEFAULT gen_random_uuid() NOT NULL;',
                'ALTER TABLE analytics_pageview ADD PRIMARY KEY (id);',
            ],
            reverse_sql=[
                'ALTER TABLE analytics_pageview DROP CONSTRAINT IF EXISTS analytics_pageview_pkey;',
                'ALTER TABLE analytics_pageview DROP COLUMN id;',
                'ALTER TABLE analytics_pageview ADD COLUMN id bigserial NOT NULL;',
                'ALTER TABLE analytics_pageview ADD PRIMARY KEY (id);',
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='pageview',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='pageview',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['timestamp', 'path'], name='analytics_p_timesta_cd14c8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_key', 'timestamp'], name='analytics_p_session_982099_idx'),
        ),
    ]
