# Generated by Django 2.0.2 on 2018-02-18 12:58

from django.db import connection, migrations


def move_welcome_message_forward(apps, schema_editor):
    """Move welcome_msg from Tournament to TournamentPreferenceModel.
    Only runs on PostgreSQL (uses ON CONFLICT upsert syntax)."""
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "INSERT INTO options_tournamentpreferencemodel "
        "(section, name, raw_value, instance_id) "
        "SELECT 'public_features', 'welcome_message', welcome_msg, id "
        "FROM tournaments_tournament "
        "ON CONFLICT (instance_id, section, name) "
        "DO UPDATE SET raw_value=EXCLUDED.raw_value;"
    )


def move_welcome_message_backward(apps, schema_editor):
    """Reverse: copy welcome_message pref back to Tournament.welcome_msg."""
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "UPDATE tournaments_tournament t "
        "SET welcome_msg=o.raw_value "
        "FROM options_tournamentpreferencemodel o "
        "WHERE o.instance_id=t.id "
        "AND o.section='public_features' "
        "AND o.name='welcome_message';"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            move_welcome_message_forward,
            move_welcome_message_backward,
        ),
    ]
