# Generated by Django 5.2.7 on 2026-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_create_organization_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_workspace_enabled',
            field=models.BooleanField(db_index=True, default=False, help_text='When enabled, this organization is accessible via its own subdomain.', verbose_name='workspace enabled'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('tabmaster', 'Tabmaster'), ('editor', 'Editor'), ('viewer', 'Viewer'), ('member', 'Member')], default='member', max_length=20, verbose_name='role'),
        ),
    ]
