# Generated by Django 5.2.12 on 2026-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_add_workspace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deactivation_reason',
            field=models.TextField(blank=True, default='', verbose_name='deactivation reason'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive organizations are hidden from the registration flow.', verbose_name='active'),
        ),
    ]
