# Generated by Django 5.2.7 on 2026-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_club_member_profile_invitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_organiz_00b44d_idx',
            old_name='org_inv_org_accepted_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='organizatio_email_6f758b_idx',
            old_name='org_inv_email_org_idx',
        ),
        migrations.AlterField(
            model_name='clubmemberprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
