# Generated by Django 5.2.7 on 2026-05-19 13:30

import django.db.models.deletion
import utils.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_rename_org_inv_org_accepted_idx_organizatio_organiz_00b44d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='department')),
                ('batch', models.CharField(blank=True, default='', max_length=50, verbose_name='batch / session')),
                ('designation', models.CharField(blank=True, default='', max_length=100, verbose_name='designation')),
                ('speaker_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='speaker rating')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_members', to='organizations.organization', verbose_name='organization')),
                ('user', models.ForeignKey(blank=True, help_text='Optional linked platform account for this club member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'club member',
                'verbose_name_plural': 'club members',
                'ordering': ['organization_id', 'full_name'],
                'constraints': [utils.models.UniqueConstraint(fields=('organization', 'user'), name='organiz_clubmember_organization__user_uniq')],
            },
        ),
    ]
