# Generated by Django 5.2.7 on 2026-05-19 15:28

import utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_orgform_orgformresponse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgform',
            name='unique_orgform_org_slug',
        ),
        migrations.AlterField(
            model_name='orgform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='is_accepting',
            field=models.BooleanField(default=False, help_text='When on, the public submission URL is active.', verbose_name='accepting submissions'),
        ),
        migrations.AlterField(
            model_name='orgform',
            name='is_confirmation_public',
            field=models.BooleanField(default=False, help_text='When on, the public confirmation board is visible.', verbose_name='confirmation board public'),
        ),
        migrations.AlterField(
            model_name='orgformresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='orgform',
            constraint=utils.models.UniqueConstraint(fields=('organization', 'slug'), name='organiz_orgform_organization__slug_uniq'),
        ),
    ]
