# Generated by Django 5.2.13 on 2026-05-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_remove_orgform_unique_orgform_org_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgformresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waiting', 'Waiting')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
