# Generated by Django 5.2.13 on 2026-05-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_add_waiting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgform',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
