# Generated by Django 5.2.13 on 2026-05-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_add_form_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgform',
            name='registration_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='registration fields'),
        ),
        migrations.CreateModel(
            name='OrgRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='registration data')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_reg_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='organizations.orgformresponse', verbose_name='pre-registration response')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
