# Generated by Django 5.2.7 on 2026-02-14 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('color', models.CharField(default='#663da0', help_text='Hex color for tag badge', max_length=7, verbose_name='color hex')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
            ],
            options={
                'verbose_name': 'forum tag',
                'verbose_name_plural': 'forum tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=5, verbose_name='vote type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'forum vote',
                'verbose_name_plural': 'forum votes',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('verified_ca', 'Verified CA'), ('chief_adj', 'Chief Adjudicator'), ('national_team', 'National Team'), ('worlds_breaker', 'Worlds Breaker'), ('judge_panelist', 'Judge Panelist'), ('tournament_winner', 'Tournament Winner'), ('experienced', 'Experienced Debater')], max_length=30, verbose_name='badge type')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('evidence', models.TextField(blank=True, help_text='Link or description proving this credential', verbose_name='evidence')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='awarded at')),
            ],
            options={
                'verbose_name': 'user badge',
                'verbose_name_plural': 'user badges',
            },
        ),
        migrations.CreateModel(
            name='ForumBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'forum bookmark',
                'verbose_name_plural': 'forum bookmarks',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('opening', 'Opening Post'), ('counter', 'Counterargument'), ('support', 'Support'), ('clarification', 'Clarification'), ('example', 'Example'), ('rebuttal', 'Rebuttal'), ('extension', 'Extension'), ('framework', 'Framework'), ('weighing', 'Weighing')], default='opening', max_length=20, verbose_name='post type')),
                ('content', models.TextField(verbose_name='content')),
                ('is_edited', models.BooleanField(default=False, verbose_name='edited')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('parent', models.ForeignKey(blank=True, help_text='The post this is replying to (for argument tree structure)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.forumpost', verbose_name='parent post')),
            ],
            options={
                'verbose_name': 'forum post',
                'verbose_name_plural': 'forum posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('off_topic', 'Off-topic'), ('misinfo', 'Misinformation'), ('other', 'Other')], max_length=20, verbose_name='reason')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.forumpost', verbose_name='post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'verbose_name': 'forum report',
                'verbose_name_plural': 'forum reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='slug')),
                ('debate_format', models.CharField(choices=[('bp', 'British Parliamentary'), ('wsdc', 'World Schools'), ('ap', 'Australs / Asian Parliamentary'), ('pf', 'Public Forum'), ('ld', 'Lincoln-Douglas'), ('policy', 'Policy'), ('cp', 'Canadian Parliamentary'), ('other', 'Other')], default='bp', max_length=20, verbose_name='debate format')),
                ('topic_category', models.CharField(choices=[('theory', 'Theory'), ('strategy', 'Strategy'), ('motions', 'Motions'), ('judge_issues', 'Judge Issues'), ('meta', 'Meta'), ('case_study', 'Case Study'), ('training', 'Training')], default='strategy', max_length=20, verbose_name='topic category')),
                ('skill_level', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All Levels')], default='all', max_length=20, verbose_name='skill level')),
                ('region', models.CharField(blank=True, help_text='Geographic region relevance (optional)', max_length=100, verbose_name='region')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('is_locked', models.BooleanField(default=False, verbose_name='locked')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'forum thread',
                'verbose_name_plural': 'forum threads',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
