# Generated by Django 5.2.7 on 2026-02-14 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('motionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='linked_motion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='motionbank.motionentry', verbose_name='linked motion'),
        ),
        migrations.AddField(
            model_name='forumthread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.forumtag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.forumthread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='forumbookmark',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='forum.forumthread', verbose_name='thread'),
        ),
        migrations.AddField(
            model_name='forumvote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.forumpost', verbose_name='post'),
        ),
        migrations.AddField(
            model_name='forumvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_votes', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_badges', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_verified', to=settings.AUTH_USER_MODEL, verbose_name='verified by'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['-created_at'], name='forum_forum_created_130b31_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['debate_format', 'topic_category'], name='forum_forum_debate__84a905_idx'),
        ),
        migrations.AddIndex(
            model_name='forumthread',
            index=models.Index(fields=['skill_level'], name='forum_forum_skill_l_7bf9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['thread', 'created_at'], name='forum_forum_thread__31fcba_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['parent'], name='forum_forum_parent__f64ce8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='forumbookmark',
            unique_together={('user', 'thread')},
        ),
        migrations.AlterUniqueTogether(
            name='forumvote',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge_type')},
        ),
    ]
