# Generated by Django 5.2.7 on 2026-02-23 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The post this is replying to (for argument tree structure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='forum.forumpost', verbose_name='parent post'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddConstraint(
            model_name='forumreport',
            constraint=models.UniqueConstraint(fields=('reporter', 'post'), name='unique_report_per_user'),
        ),
    ]
