# Generated by Django 5.2.7 on 2026-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_fix_cascade_deletes_and_add_report_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumreport',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='resolved'),
        ),
    ]
