# Generated by Copilot on 2025-11-06
from django.db import migrations, models
import django.db.models.deletion
import uuid
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0031_add_tournament_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCreationRequest',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('form_data', models.JSONField()),
                ('otp_code', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=16, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_creation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tournament creation request',
                'verbose_name_plural': 'tournament creation requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
