# Generated by Django 5.2.7 on 2026-02-20 06:38

import tournaments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0034_tournament_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='If enabled, this tournament appears in the public showcase and is visible to all users (even those without a role).', verbose_name='publicly listed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='retention_exempt',
            field=models.BooleanField(default=False, help_text='If enabled, this tournament will never be automatically deleted by the retention policy.', verbose_name='exempt from auto-deletion'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scheduled_for_deletion_at',
            field=models.DateTimeField(blank=True, help_text='If set, the tournament is in the grace period and will be deleted after this timestamp.', null=True, verbose_name='scheduled for deletion at'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(help_text='The sub-URL of the tournament. Use only lowercase letters, numbers, and hyphens, e.g. "australs-2016"', unique=True, validators=[tournaments.models.validate_tournament_slug, tournaments.models.validate_dns_safe_slug], verbose_name='slug'),
        ),
    ]
