# Generated by Django 5.2.7 on 2026-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0035_tournament_is_listed_tournament_retention_exempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='completed',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the round is over, which normally means all results have been entered and confirmed', verbose_name='completed'),
        ),
        migrations.AlterField(
            model_name='round',
            name='stage',
            field=models.CharField(choices=[('P', 'Preliminary'), ('E', 'Elimination')], db_index=True, default='P', help_text='Preliminary = inrounds, elimination = outrounds', max_length=1, verbose_name='stage'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=False, help_text='If enabled, this tournament appears in the public showcase and is visible to all users (even those without a role).', verbose_name='publicly listed'),
        ),
    ]
