# Generated by Django 5.2.7 on 2026-03-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_create_organization_models'),
        ('tournaments', '0036_add_missing_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this tournament belongs to. All org members get access based on their org role.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization', verbose_name='organization'),
        ),
    ]
