# Generated by Django 5.2.7 on 2026-03-04 09:11
"""Data migration: backfill existing tournaments with organizations.

For each user who owns tournaments, create a personal Organization and
assign all their tournaments to it. Also creates OrganizationMembership
with OWNER role.

Tournaments without an owner get assigned to a shared "Unassigned" org.
"""

from django.db import migrations


def backfill_orgs(apps, schema_editor):
    Tournament = apps.get_model('tournaments', 'Tournament')
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationMembership = apps.get_model('organizations', 'OrganizationMembership')

    # Collect unique owners
    owner_ids = (
        Tournament.objects
        .filter(owner__isnull=False, organization__isnull=True)
        .values_list('owner_id', flat=True)
        .distinct()
    )

    User = apps.get_model('auth', 'User')
    for owner_id in owner_ids:
        user = User.objects.get(pk=owner_id)
        slug = f"org-{user.username}"[:80]
        # Ensure unique slug
        base_slug = slug
        counter = 1
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"[:80]
            counter += 1

        org = Organization.objects.create(
            name=f"{user.username}'s Organization",
            slug=slug,
        )
        OrganizationMembership.objects.get_or_create(
            organization=org,
            user=user,
            defaults={'role': 'owner'},
        )
        # Assign all this owner's tournaments to the org
        Tournament.objects.filter(owner=user, organization__isnull=True).update(
            organization=org,
        )

    # Handle orphan tournaments (no owner)
    orphans = Tournament.objects.filter(owner__isnull=True, organization__isnull=True)
    if orphans.exists():
        unassigned_org, _ = Organization.objects.get_or_create(
            slug='unassigned',
            defaults={'name': 'Unassigned Tournaments'},
        )
        orphans.update(organization=unassigned_org)


def reverse_backfill(apps, schema_editor):
    """Reverse is a no-op — we don't delete orgs on reverse."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0037_add_organization_fk'),
        ('organizations', '0001_create_organization_models'),
    ]

    operations = [
        migrations.RunPython(backfill_orgs, reverse_backfill),
    ]
