# Generated by Django 5.2.7 on 2026-05-19 13:30

import django.db.models.deletion
import utils.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0039_enforce_organization_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start_date', models.DateField(blank=True, null=True, verbose_name='event start date')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='event end date')),
                ('registration_open', models.DateTimeField(blank=True, null=True, verbose_name='registration open')),
                ('registration_close', models.DateTimeField(blank=True, null=True, verbose_name='registration close')),
                ('event_format', models.CharField(blank=True, default='', max_length=100, verbose_name='format')),
                ('venue', models.CharField(blank=True, default='', max_length=200, verbose_name='venue')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('organization', 'Organization'), ('public', 'Public')], default='organization', max_length=20, verbose_name='visibility')),
                ('registration_type', models.CharField(choices=[('open', 'Open'), ('invite_only', 'Invite-only'), ('approval', 'Approval required')], default='open', max_length=20, verbose_name='registration type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=30, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'tournament metadata',
                'verbose_name_plural': 'tournament metadata',
            },
        ),
        migrations.CreateModel(
            name='TournamentAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120, verbose_name='action')),
                ('entity_type', models.CharField(max_length=120, verbose_name='entity type')),
                ('entity_id', models.CharField(blank=True, default='', max_length=120, verbose_name='entity id')),
                ('old_value', models.JSONField(blank=True, default=dict, verbose_name='old value')),
                ('new_value', models.JSONField(blank=True, default=dict, verbose_name='new value')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'tournament audit log',
                'verbose_name_plural': 'tournament audit logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', 'created_at'], name='tournaments_tournam_cf36dc_idx'), models.Index(fields=['entity_type', 'entity_id'], name='tournaments_entity__95be07_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentStaffInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('role', models.CharField(choices=[('tab_director', 'Tab Director'), ('assistant_tab', 'Assistant Tab'), ('equity', 'Equity'), ('convenor', 'Convenor'), ('observer', 'Observer')], max_length=30, verbose_name='role')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_tournament_staff_invitations', to=settings.AUTH_USER_MODEL, verbose_name='accepted by')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_staff_invitations', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'tournament staff invitation',
                'verbose_name_plural': 'tournament staff invitations',
                'indexes': [models.Index(fields=['tournament', 'accepted_at'], name='tournaments_tournam_b64306_idx'), models.Index(fields=['email', 'tournament'], name='tournaments_email_f478de_idx')],
            },
        ),
        migrations.CreateModel(
            name='TournamentStaffMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tab_director', 'Tab Director'), ('assistant_tab', 'Assistant Tab'), ('equity', 'Equity'), ('convenor', 'Convenor'), ('observer', 'Observer')], max_length=30, verbose_name='role')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_tournament_staff_memberships', to=settings.AUTH_USER_MODEL, verbose_name='invited by')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='tournaments.tournament', verbose_name='tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_staff_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'tournament staff membership',
                'verbose_name_plural': 'tournament staff memberships',
                'indexes': [models.Index(fields=['tournament', 'role'], name='tournaments_tournam_5fb136_idx')],
                'constraints': [utils.models.UniqueConstraint(fields=('tournament', 'user', 'role'), name='tournam_tournamentstaffmembership_tournament__user__role_uniq')],
            },
        ),
    ]
