# Generated by Django 5.2.12 on 2026-04-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0039_enforce_organization_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('tab', 'Tab Room'), ('organizers', 'Organizers'), ('adjudicators', 'Adjudicators')], max_length=20, verbose_name='room type')),
                ('pin', models.CharField(help_text='Required to enter this room. Share only with intended participants.', max_length=10, verbose_name='PIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='tournaments.tournament', verbose_name='tournament')),
            ],
            options={
                'verbose_name': 'chat room',
                'verbose_name_plural': 'chat rooms',
                'unique_together': {('tournament', 'room_type')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.chatroom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'room session',
                'verbose_name_plural': 'room sessions',
                'unique_together': {('session_key', 'room')},
            },
        ),
    ]
