# Generated by Django 4.2 on 2026-05-10

import decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='lemonsqueezy', max_length=32)),
                ('external_reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('event_name_last', models.CharField(blank=True, max_length=100)),
                ('donation_type', models.CharField(choices=[('one_time', 'One-Time'), ('subscription', 'Subscription')], db_index=True, default='one_time', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=10)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('lemon_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('lemon_subscription_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('lemon_customer_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checkout_identifier', models.CharField(blank=True, max_length=120)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('variant_name', models.CharField(blank=True, max_length=255)),
                ('donated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'donation transaction',
                'verbose_name_plural': 'donation transactions',
                'ordering': ['-donated_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LemonWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('event_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('lemon_object_type', models.CharField(blank=True, max_length=100)),
                ('lemon_object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='donations.donationtransaction')),
            ],
            options={
                'verbose_name': 'Lemon Squeezy webhook event',
                'verbose_name_plural': 'Lemon Squeezy webhook events',
                'ordering': ['-received_at'],
            },
        ),
    ]
