# Generated by Django 5.2.7 on 2026-02-14 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0034_tournament_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebatePassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='display name')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code for flag', max_length=3, verbose_name='country code')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('primary_format', models.CharField(choices=[('bp', 'British Parliamentary'), ('wsdc', 'World Schools'), ('ap', 'Australs / Asian Parliamentary'), ('pf', 'Public Forum'), ('ld', 'Lincoln-Douglas'), ('policy', 'Policy'), ('cp', 'Canadian Parliamentary'), ('multi', 'Multiple Formats')], default='bp', max_length=20, verbose_name='primary format')),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3-5 years)'), ('expert', 'Expert (5+ years)'), ('professional', 'Professional / Coach')], default='beginner', max_length=20, verbose_name='experience level')),
                ('is_speaker', models.BooleanField(default=True, verbose_name='speaker')),
                ('is_judge', models.BooleanField(default=False, verbose_name='judge / adjudicator')),
                ('is_ca', models.BooleanField(default=False, verbose_name='chief adjudicator')),
                ('is_coach', models.BooleanField(default=False, verbose_name='coach / trainer')),
                ('is_public', models.BooleanField(default=True, verbose_name='public profile')),
                ('show_scores', models.BooleanField(default=True, verbose_name='show scores')),
                ('show_analytics', models.BooleanField(default=True, verbose_name='show analytics')),
                ('avatar_url', models.URLField(blank=True, verbose_name='avatar URL')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debate_passport', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'debate passport',
                'verbose_name_plural': 'debate passports',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200, verbose_name='partner name')),
                ('tournaments_together', models.PositiveIntegerField(default=0, verbose_name='tournaments together')),
                ('rounds_together', models.PositiveIntegerField(default=0, verbose_name='rounds together')),
                ('wins_together', models.PositiveIntegerField(default=0, verbose_name='wins together')),
                ('total_speaker_score', models.FloatField(default=0, verbose_name='total combined speaker score')),
                ('partner_passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnerships_as_partner', to='passport.debatepassport', verbose_name='partner passport')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships', to='passport.debatepassport', verbose_name='passport')),
            ],
            options={
                'verbose_name': 'partnership',
                'verbose_name_plural': 'partnerships',
                'ordering': ['-tournaments_together'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200, verbose_name='tournament name')),
                ('tournament_format', models.CharField(choices=[('bp', 'British Parliamentary'), ('wsdc', 'World Schools'), ('ap', 'Australs / Asian Parliamentary'), ('pf', 'Public Forum'), ('ld', 'Lincoln-Douglas'), ('policy', 'Policy'), ('cp', 'Canadian Parliamentary'), ('multi', 'Multiple Formats')], max_length=20, verbose_name='format')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('num_rounds', models.PositiveIntegerField(default=0, verbose_name='number of rounds')),
                ('role', models.CharField(choices=[('speaker', 'Speaker'), ('judge', 'Judge / Adjudicator'), ('ca', 'Chief Adjudicator'), ('dca', 'Deputy Chief Adjudicator'), ('tab_dir', 'Tab Director'), ('coach', 'Coach')], default='speaker', max_length=10, verbose_name='role')),
                ('team_name', models.CharField(blank=True, max_length=200, verbose_name='team name')),
                ('partner_names', models.JSONField(blank=True, default=list, verbose_name='partner names')),
                ('broke', models.BooleanField(default=False, verbose_name='broke (reached elimination rounds)')),
                ('break_category', models.CharField(blank=True, help_text="e.g., 'Open Break', 'ESL Break', 'EFL Break'", max_length=100, verbose_name='break category')),
                ('final_rank', models.CharField(blank=True, help_text="e.g., 'Grand Finalist', 'Semi-finalist', '15th'", max_length=50, verbose_name='final rank')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('internal_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passport_participations', to='tournaments.tournament', verbose_name='linked tournament')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='passport.debatepassport', verbose_name='passport')),
            ],
            options={
                'verbose_name': 'tournament participation',
                'verbose_name_plural': 'tournament participations',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JudgeBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='round number')),
                ('round_name', models.CharField(blank=True, max_length=100, verbose_name='round name')),
                ('was_chair', models.BooleanField(default=False, verbose_name='was chair')),
                ('panel_size', models.PositiveIntegerField(default=1, verbose_name='panel size')),
                ('agreed_with_majority', models.BooleanField(default=True, verbose_name='agreed with majority')),
                ('scores_given', models.JSONField(blank=True, default=dict, verbose_name='scores given')),
                ('motion_text', models.TextField(blank=True, verbose_name='motion')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_ballots', to='passport.tournamentparticipation', verbose_name='participation')),
            ],
            options={
                'verbose_name': 'judge ballot',
                'verbose_name_plural': 'judge ballots',
                'ordering': ['participation', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tournaments', models.PositiveIntegerField(default=0, verbose_name='total tournaments')),
                ('total_rounds', models.PositiveIntegerField(default=0, verbose_name='total rounds')),
                ('break_rate', models.FloatField(default=0, verbose_name='break rate (%)')),
                ('average_speaker_score', models.FloatField(default=0, verbose_name='average speaker score')),
                ('highest_speaker_score', models.FloatField(default=0, verbose_name='highest speaker score')),
                ('overall_win_rate', models.FloatField(default=0, verbose_name='overall win rate (%)')),
                ('gov_win_rate', models.FloatField(default=0, verbose_name='gov/prop win rate (%)')),
                ('opp_win_rate', models.FloatField(default=0, verbose_name='opp win rate (%)')),
                ('format_distribution', models.JSONField(blank=True, default=dict, verbose_name='format distribution')),
                ('skill_framing', models.FloatField(default=50, verbose_name='framing skill')),
                ('skill_clash', models.FloatField(default=50, verbose_name='clash skill')),
                ('skill_extension', models.FloatField(default=50, verbose_name='extension quality')),
                ('skill_weighing', models.FloatField(default=50, verbose_name='weighing skill')),
                ('skill_rebuttal', models.FloatField(default=50, verbose_name='rebuttal skill')),
                ('skill_strategy', models.FloatField(default=50, verbose_name='strategy skill')),
                ('skill_delivery', models.FloatField(default=50, verbose_name='delivery skill')),
                ('judge_total_rounds', models.PositiveIntegerField(default=0, verbose_name='total judging rounds')),
                ('judge_chair_rate', models.FloatField(default=0, verbose_name='chair rate (%)')),
                ('judge_avg_score_given', models.FloatField(default=0, verbose_name='average score given')),
                ('judge_score_variance', models.FloatField(default=0, verbose_name='score variance')),
                ('judge_majority_agreement', models.FloatField(default=0, verbose_name='majority agreement rate (%)')),
                ('performance_trend', models.JSONField(blank=True, default=list, verbose_name='performance trend')),
                ('last_computed', models.DateTimeField(auto_now=True, verbose_name='last computed')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cached_stats', to='passport.debatepassport', verbose_name='passport')),
            ],
            options={
                'verbose_name': 'user stats',
                'verbose_name_plural': 'user stats',
            },
        ),
        migrations.CreateModel(
            name='RoundPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='round number')),
                ('round_name', models.CharField(blank=True, help_text="e.g., 'Round 1', 'Quarterfinals'", max_length=100, verbose_name='round name')),
                ('side', models.CharField(choices=[('gov', 'Government / Proposition'), ('opp', 'Opposition'), ('og', 'Opening Government'), ('oo', 'Opening Opposition'), ('cg', 'Closing Government'), ('co', 'Closing Opposition')], max_length=5, verbose_name='side')),
                ('position', models.CharField(blank=True, choices=[('pm', 'Prime Minister / 1st Prop'), ('dpm', 'Deputy PM / 2nd Prop'), ('lo', 'Leader of Opposition / 1st Opp'), ('dlo', 'Deputy LO / 2nd Opp'), ('mg', 'Member of Government / 3rd Prop'), ('gw', 'Government Whip / 4th Prop'), ('mo', 'Member of Opposition / 3rd Opp'), ('ow', 'Opposition Whip / 4th Opp'), ('first', '1st Speaker'), ('second', '2nd Speaker'), ('third', '3rd Speaker'), ('reply', 'Reply Speaker')], max_length=10, verbose_name='speaking position')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('1st', '1st Place (BP)'), ('2nd', '2nd Place (BP)'), ('3rd', '3rd Place (BP)'), ('4th', '4th Place (BP)')], max_length=5, verbose_name='result')),
                ('speaker_score', models.FloatField(blank=True, null=True, verbose_name='speaker score')),
                ('average_score_in_round', models.FloatField(blank=True, null=True, verbose_name='average speaker score in round')),
                ('motion_text', models.TextField(blank=True, verbose_name='motion')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_performances', to='passport.tournamentparticipation', verbose_name='participation')),
            ],
            options={
                'verbose_name': 'round performance',
                'verbose_name_plural': 'round performances',
                'ordering': ['participation', 'round_number'],
                'unique_together': {('participation', 'round_number')},
            },
        ),
    ]
