# Generated by Django 5.2.7 on 2026-05-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_rename_org_inv_org_accepted_idx_organizatio_organiz_00b44d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('format', models.CharField(choices=[('bp', 'British Parliamentary'), ('ap', 'Asian Parliamentary'), ('wsdc', 'WSDC'), ('msdc', 'MSDC'), ('oxford', 'Oxford'), ('other', 'Other')], default='bp', max_length=20, verbose_name='format')),
                ('venue', models.CharField(blank=True, default='', max_length=200, verbose_name='venue')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='organizations.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'practice session',
                'verbose_name_plural': 'practice sessions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Room 1', max_length=50, verbose_name='name')),
                ('motion', models.TextField(blank=True, default='', verbose_name='motion')),
                ('seq', models.PositiveSmallIntegerField(default=1, verbose_name='order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='practice.practicesession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'session room',
                'verbose_name_plural': 'session rooms',
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('debater', 'Debater'), ('adjudicator', 'Adjudicator')], default='debater', max_length=20, verbose_name='role')),
                ('team_name', models.CharField(blank=True, default='', max_length=100, verbose_name='team name')),
                ('attended', models.BooleanField(default=True, verbose_name='attended')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to='organizations.organizationmembership', verbose_name='member')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='practice.practicesession', verbose_name='session')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='practice.sessionroom', verbose_name='room')),
            ],
            options={
                'verbose_name': 'session participant',
                'verbose_name_plural': 'session participants',
            },
        ),
        migrations.CreateModel(
            name='SpeakerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Overall speaker score for this debate.', max_digits=5, null=True, verbose_name='speaker score')),
                ('reply_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='reply score')),
                ('notes', models.TextField(blank=True, default='', verbose_name='adjudicator notes')),
                ('won', models.BooleanField(blank=True, null=True, verbose_name='won debate')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='practice.sessionparticipant', verbose_name='participant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_practice_scores', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'speaker score',
                'verbose_name_plural': 'speaker scores',
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['organization', 'date'], name='practice_pr_organiz_f4b106_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['organization', 'status'], name='practice_pr_organiz_2df7e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionroom',
            unique_together={('session', 'seq')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'membership')},
        ),
    ]
