from django.urls import path

from . import views

urlpatterns = [
    path('',
        views.IEDashboardView.as_view(),
        name='ie-admin-dashboard'),
    path('setup/',
        views.IESetupView.as_view(),
        name='ie-admin-setup'),
    # Tournament Prep — Participant Management
    path('prep/',
        views.IETournamentPrepView.as_view(),
        name='ie-admin-prep'),
    path('prep/all/',
        views.IEPrepAllView.as_view(),
        name='ie-prep-all'),
    path('prep/institutions/',
        views.IEPrepInstitutionsView.as_view(),
        name='ie-prep-institutions'),
    path('prep/institutions/<int:inst_id>/',
        views.IEPrepInstitutionsView.as_view(),
        name='ie-prep-institution-detail'),
    path('prep/speakers/',
        views.IEPrepSpeakersView.as_view(),
        name='ie-prep-speakers'),
    path('prep/speakers/<int:spk_id>/',
        views.IEPrepSpeakersView.as_view(),
        name='ie-prep-speaker-detail'),
    path('prep/judges/',
        views.IEPrepJudgesView.as_view(),
        name='ie-prep-judges'),
    path('prep/judges/<int:adj_id>/',
        views.IEPrepJudgesView.as_view(),
        name='ie-prep-judge-detail'),
    path('prep/import/',
        views.IEPrepImportView.as_view(),
        name='ie-prep-import'),
    # Event Management
    path('<int:event_id>/entries/',
        views.IEEntryManagerView.as_view(),
        name='ie-admin-entries'),
    path('<int:event_id>/draw/<int:round_number>/',
        views.IERoomDrawView.as_view(),
        name='ie-admin-draw'),
    path('<int:event_id>/ballot/<int:room_id>/',
        views.IEBallotView.as_view(),
        name='ie-admin-ballot'),
    path('<int:event_id>/standings/',
        views.IEAdminStandingsView.as_view(),
        name='ie-admin-standings'),
    path('<int:event_id>/finalists/',
        views.IEFinalistsView.as_view(),
        name='ie-admin-finalists'),
    path('<int:event_id>/judge-links/<int:round_number>/',
        views.IEGenerateJudgeLinksView.as_view(),
        name='ie-admin-judge-links'),
    path('<int:event_id>/judge-links/<int:round_number>/page/',
        views.IEJudgeLinksPageView.as_view(),
        name='ie-admin-judge-links-page'),
]
