# Generated by Django 5.2.7 on 2026-02-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentDeletionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField(help_text='PK of the tournament (may no longer exist).', verbose_name='tournament ID')),
                ('slug', models.CharField(max_length=200, verbose_name='slug')),
                ('name', models.CharField(max_length=200, verbose_name='tournament name')),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='owner email')),
                ('owner_username', models.CharField(blank=True, default='', max_length=150, verbose_name='owner username')),
                ('team_count', models.PositiveIntegerField(default=0)),
                ('round_count', models.PositiveIntegerField(default=0)),
                ('debate_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('EXPORTED', 'Exported'), ('DELETED', 'Deleted'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (exempt)'), ('DRY_RUN', 'Dry run')], max_length=20, verbose_name='status')),
                ('archive_path', models.CharField(blank=True, default='', help_text='Path or URL to the exported archive (if any).', max_length=500, verbose_name='archive path')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'tournament deletion log',
                'verbose_name_plural': 'tournament deletion logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament_id'], name='retention_t_tournam_69bf26_idx'), models.Index(fields=['slug'], name='retention_t_slug_9e7738_idx'), models.Index(fields=['status'], name='retention_t_status_93e964_idx')],
            },
        ),
    ]
