# Generated by Django 5.2.7 on 2026-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0010_alter_debateteam_side_alter_teamsideallocation_side'),
        ('participants', '0029_alter_person_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='debateteam',
            constraint=models.UniqueConstraint(fields=('debate', 'side'), name='unique_debate_side'),
        ),
    ]
