# Generated by Django 5.2.7 on 2026-02-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0011_p0_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='result_status',
            field=models.CharField(choices=[('N', 'none'), ('P', 'postponed'), ('D', 'draft'), ('C', 'confirmed')], db_index=True, default='N', max_length=1, verbose_name='result status'),
        ),
    ]
