# Generated by Django 5.2.7 on 2026-02-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0005_alter_identifier_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identifier',
            options={},
        ),
    ]
