# Generated by Django 5.2.7 on 2026-02-14 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motions', '0006_alter_debateteammotionpreference_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='motion text')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='slug')),
                ('info_slide', models.TextField(blank=True, verbose_name='info slide')),
                ('format', models.CharField(choices=[('bp', 'British Parliamentary'), ('wsdc', 'World Schools'), ('ap', 'Australs / Asian Parliamentary'), ('pf', 'Public Forum'), ('ld', 'Lincoln-Douglas'), ('policy', 'Policy'), ('cp', 'Canadian Parliamentary'), ('other', 'Other')], default='bp', max_length=20, verbose_name='debate format')),
                ('motion_type', models.CharField(choices=[('policy', 'Policy'), ('value', 'Value'), ('actor', 'Actor-Specific'), ('thb', 'This House Believes'), ('thw', 'This House Would'), ('thbt', 'This House Believes That'), ('thr', 'This House Regrets'), ('ths', 'This House Supports'), ('factual', 'Factual'), ('other', 'Other')], default='thw', max_length=20, verbose_name='motion type')),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Moderate'), (4, 'Hard'), (5, 'Expert')], default=3, verbose_name='difficulty')),
                ('prep_type', models.CharField(choices=[('prepared', 'Prepared'), ('impromptu', 'Impromptu')], default='impromptu', max_length=20, verbose_name='preparation type')),
                ('tournament_name', models.CharField(blank=True, max_length=200, verbose_name='tournament name')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('round_info', models.CharField(blank=True, help_text="e.g., 'Grand Final', 'Round 3', 'Quarterfinals'", max_length=100, verbose_name='round info')),
                ('theme_tags', models.JSONField(blank=True, default=list, help_text="e.g., ['economics', 'environment', 'human rights']", verbose_name='theme tags')),
                ('source', models.CharField(blank=True, help_text='Where this motion was collected from', max_length=300, verbose_name='source')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('internal_motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motionbank_entry', to='motions.motion', verbose_name='linked internal motion')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_motions', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'motion entry',
                'verbose_name_plural': 'motion entries',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis', models.JSONField(default=dict, help_text='JSON structure:\n        {\n            "hidden_assumptions": ["..."],\n            "model_problems": ["..."],\n            "clash_areas": ["..."],\n            "framing_mistakes": ["..."],\n            "gov_approach": { "structure": "...", "key_args": ["..."] },\n            "opp_approach": { "structure": "...", "key_args": ["..."] },\n            "definition_traps": ["..."],\n            "burden_split": "...",\n            "likely_extensions": { "OG": "...", "OO": "...", "CG": "...", "CO": "..." },\n            "weighing_options": ["..."],\n            "suggested_pois": ["..."],\n            "difficulty_rationale": "..."\n        }', verbose_name='AI analysis')),
                ('model_used', models.CharField(blank=True, max_length=100, verbose_name='AI model used')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='confidence score')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='motionbank.motionentry', verbose_name='motion')),
            ],
            options={
                'verbose_name': 'motion analysis',
                'verbose_name_plural': 'motion analyses',
            },
        ),
        migrations.CreateModel(
            name='CaseOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('gov', 'Government / Proposition'), ('opp', 'Opposition'), ('og', 'Opening Government'), ('oo', 'Opening Opposition'), ('cg', 'Closing Government'), ('co', 'Closing Opposition')], max_length=5, verbose_name='side')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(help_text='Structured case outline with arguments, examples, weighing', verbose_name='case outline content')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='upvotes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_outlines', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_outlines', to='motionbank.motionentry', verbose_name='motion')),
            ],
            options={
                'verbose_name': 'case outline',
                'verbose_name_plural': 'case outlines',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='1-5 star rating', verbose_name='score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='motionbank.motionentry', verbose_name='motion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'motion rating',
                'verbose_name_plural': 'motion ratings',
            },
        ),
        migrations.CreateModel(
            name='MotionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_practiced', models.PositiveIntegerField(default=0, verbose_name='times practiced')),
                ('times_used_in_tournaments', models.PositiveIntegerField(default=0, verbose_name='times used')),
                ('forum_thread_count', models.PositiveIntegerField(default=0, verbose_name='forum threads')),
                ('average_rating', models.FloatField(default=0.0, verbose_name='average rating')),
                ('total_ratings', models.PositiveIntegerField(default=0, verbose_name='total ratings')),
                ('gov_win_rate', models.FloatField(blank=True, help_text='Percentage of times gov/prop side won', null=True, verbose_name='gov win rate')),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='motionbank.motionentry', verbose_name='motion')),
            ],
            options={
                'verbose_name': 'motion stats',
                'verbose_name_plural': 'motion stats',
            },
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_practiced', models.CharField(blank=True, choices=[('gov', 'Government / Proposition'), ('opp', 'Opposition'), ('og', 'Opening Government'), ('oo', 'Opening Opposition'), ('cg', 'Closing Government'), ('co', 'Closing Opposition')], max_length=5, verbose_name='side practiced')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('motion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='motionbank.motionentry', verbose_name='motion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'practice session',
                'verbose_name_plural': 'practice sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseOutlineVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('case_outline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='motionbank.caseoutline', verbose_name='case outline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_outline_votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'case outline vote',
                'verbose_name_plural': 'case outline votes',
                'unique_together': {('user', 'case_outline')},
            },
        ),
        migrations.AddIndex(
            model_name='motionentry',
            index=models.Index(fields=['format', 'year'], name='motionbank__format_268918_idx'),
        ),
        migrations.AddIndex(
            model_name='motionentry',
            index=models.Index(fields=['motion_type'], name='motionbank__motion__612b06_idx'),
        ),
        migrations.AddIndex(
            model_name='motionentry',
            index=models.Index(fields=['difficulty'], name='motionbank__difficu_4f1a73_idx'),
        ),
        migrations.AddIndex(
            model_name='motionentry',
            index=models.Index(fields=['-created_at'], name='motionbank__created_3a949a_idx'),
        ),
        migrations.AddIndex(
            model_name='motionentry',
            index=models.Index(fields=['slug'], name='motionbank__slug_c17b25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='motionrating',
            unique_together={('user', 'motion')},
        ),
    ]
