# Generated by Django 5.2.7 on 2026-02-16 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motionbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., bioethics_restriction, prohibition_black_market', max_length=200, unique=True, verbose_name='archetype name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('domain_tags', models.JSONField(blank=True, default=list, verbose_name='domain tags')),
                ('trigger_features', models.JSONField(blank=True, default=dict, help_text='Keywords/patterns that activate this archetype', verbose_name='trigger features')),
                ('canonical_clashes', models.JSONField(blank=True, default=list, verbose_name='canonical clash axes')),
                ('canonical_stakeholders', models.JSONField(blank=True, default=list, verbose_name='canonical stakeholders')),
                ('gov_playbook', models.JSONField(blank=True, default=dict, verbose_name='gov playbook')),
                ('opp_playbook', models.JSONField(blank=True, default=dict, verbose_name='opp playbook')),
                ('extension_templates', models.JSONField(blank=True, default=dict, verbose_name='extension templates')),
                ('definition_traps', models.JSONField(blank=True, default=list, verbose_name='definition traps')),
                ('weighing_tools', models.JSONField(blank=True, default=list, verbose_name='weighing tools')),
                ('red_flags', models.JSONField(blank=True, default=list, help_text='Common mistakes or things to avoid', verbose_name='red flags')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='embedding vector')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'archetype',
                'verbose_name_plural': 'archetypes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArchetypeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_motion_text', models.TextField(verbose_name='example motion text')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('embedding', models.JSONField(blank=True, default=list, verbose_name='embedding vector')),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='motionbank.archetype', verbose_name='archetype')),
            ],
            options={
                'verbose_name': 'archetype example',
                'verbose_name_plural': 'archetype examples',
            },
        ),
        migrations.CreateModel(
            name='MotionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='debate format')),
                ('motion_type', models.CharField(blank=True, help_text='policy / value / actor / regret / comparative / unclear', max_length=50, verbose_name='motion type')),
                ('domain_primary', models.CharField(blank=True, help_text='bioethics / ai / econ / war / identity / etc.', max_length=100, verbose_name='primary domain')),
                ('domain_secondary', models.JSONField(blank=True, default=list, verbose_name='secondary domains')),
                ('actor', models.CharField(blank=True, help_text='e.g., the_state, UN, parents', max_length=200, verbose_name='actor')),
                ('action', models.CharField(blank=True, help_text='e.g., ban, regulate, subsidize', max_length=200, verbose_name='action')),
                ('object_field', models.CharField(blank=True, help_text='e.g., genetic engineering, social media', max_length=300, verbose_name='object')),
                ('scope', models.JSONField(blank=True, default=dict, help_text='geography, timeframe, subjects, exceptions', verbose_name='scope')),
                ('requires_model', models.BooleanField(default=False, verbose_name='requires gov model')),
                ('ambiguity_flags', models.JSONField(blank=True, default=list, verbose_name='ambiguity flags')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='extracted keywords')),
                ('constraints', models.JSONField(blank=True, default=list, verbose_name='constraints')),
                ('extracted_entities', models.JSONField(blank=True, default=dict, verbose_name='extracted entities')),
                ('confidence', models.FloatField(default=0.0, verbose_name='classifier confidence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('motion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='motionbank.motionentry', verbose_name='motion')),
            ],
            options={
                'verbose_name': 'motion profile',
                'verbose_name_plural': 'motion profiles',
            },
        ),
        migrations.CreateModel(
            name='MotionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_text', models.TextField(help_text='Stored separately so reports work for ad-hoc motions too', verbose_name='motion text')),
                ('info_slide', models.TextField(blank=True, verbose_name='info slide')),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='format')),
                ('report_json', models.JSONField(default=dict, verbose_name='report JSON')),
                ('profile_json', models.JSONField(blank=True, default=dict, verbose_name='motion profile JSON')),
                ('plan_json', models.JSONField(blank=True, default=dict, verbose_name='planner outline JSON')),
                ('validation_log', models.JSONField(blank=True, default=list, verbose_name='validation log')),
                ('model_version', models.CharField(blank=True, max_length=100, verbose_name='model version')),
                ('pipeline_duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='pipeline duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('motion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='motionbank.motionentry', verbose_name='motion')),
            ],
            options={
                'verbose_name': 'motion report',
                'verbose_name_plural': 'motion reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionReportFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 stars', verbose_name='overall rating')),
                ('was_specific', models.BooleanField(default=False, verbose_name='was motion-specific')),
                ('was_fair', models.BooleanField(default=False, verbose_name='was fair / balanced')),
                ('was_helpful', models.BooleanField(default=False, verbose_name='was helpful')),
                ('generic_section', models.CharField(blank=True, max_length=100, verbose_name='which section felt generic')),
                ('free_text', models.TextField(blank=True, verbose_name='free text feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='motionbank.motionreport', verbose_name='report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'report feedback',
                'verbose_name_plural': 'report feedback',
                'unique_together': {('report', 'user')},
            },
        ),
    ]
