# Generated by Django 5.2.7 on 2026-02-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adjallocation', '0010_alter_adjudicatoradjudicatorconflict_unique_together_and_more'),
        ('participants', '0029_alter_person_last_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='preformedpaneladjudicator',
            constraint=models.UniqueConstraint(fields=('panel', 'adjudicator'), name='unique_panel_adjudicator'),
        ),
    ]
