"""Organization role-to-permission mapping.

Maps each OrganizationMembership role to the set of tournament-level
permissions it grants.  Used by ``users.permissions.has_permission()``
to resolve org-level access without per-tournament UserPermission rows.
"""
from users.permissions import Permission

ROLE_PERMISSIONS = {
    'owner': '__all__',
    'admin': '__all__',
    'tabmaster': {
        Permission.VIEW_TEAMS, Permission.ADD_TEAMS,
        Permission.VIEW_DECODED_TEAMS,
        Permission.VIEW_ADJUDICATORS, Permission.ADD_ADJUDICATORS,
        Permission.VIEW_ROOMS, Permission.ADD_ROOMS,
        Permission.VIEW_INSTITUTIONS, Permission.ADD_INSTITUTIONS,
        Permission.VIEW_PARTICIPANTS,
        Permission.VIEW_PARTICIPANT_DECODED,
        Permission.VIEW_PARTICIPANT_CONTACT,
        Permission.VIEW_ROUNDAVAILABILITIES,
        Permission.EDIT_ROUNDAVAILABILITIES,
        Permission.VIEW_DEBATE, Permission.VIEW_ADMIN_DRAW,
        Permission.GENERATE_DEBATE, Permission.DELETE_DEBATE,
        Permission.EDIT_DEBATETEAMS,
        Permission.VIEW_DEBATEADJUDICATORS,
        Permission.EDIT_DEBATEADJUDICATORS,
        Permission.VIEW_ROOMALLOCATIONS,
        Permission.EDIT_ROOMALLOCATIONS,
        Permission.VIEW_BALLOTSUBMISSIONS,
        Permission.EDIT_BALLOTSUBMISSIONS,
        Permission.ADD_BALLOTSUBMISSIONS,
        Permission.MARK_BALLOTSUBMISSIONS,
        Permission.VIEW_NEW_BALLOTSUBMISSIONS,
        Permission.EDIT_OLD_BALLOTSUBMISSIONS,
        Permission.VIEW_RESULTS,
        Permission.VIEW_MOTION, Permission.EDIT_MOTION,
        Permission.RELEASE_DRAW, Permission.RELEASE_MOTION,
        Permission.VIEW_SETTINGS, Permission.EDIT_SETTINGS,
        Permission.EDIT_BREAK_CATEGORIES,
        Permission.GENERATE_BREAK,
        Permission.VIEW_BREAK, Permission.VIEW_BREAK_OVERVIEW,
        Permission.CONFIRM_ROUND, Permission.EDIT_ROUND,
        Permission.CREATE_ROUND, Permission.DELETE_ROUND,
        Permission.VIEW_FEEDBACK, Permission.EDIT_FEEDBACK_CONFIRM,
        Permission.VIEW_FEEDBACK_OVERVIEW,
        Permission.ADD_FEEDBACK,
        Permission.VIEW_CHECKIN, Permission.EDIT_PARTICIPANT_CHECKIN,
        Permission.SEND_EMAILS,
        Permission.VIEW_REGISTRATION,
        Permission.EDIT_QUESTIONS,
    },
    'editor': {
        Permission.VIEW_TEAMS, Permission.VIEW_ADJUDICATORS,
        Permission.VIEW_ROOMS, Permission.VIEW_INSTITUTIONS,
        Permission.VIEW_PARTICIPANTS,
        Permission.VIEW_ROUNDAVAILABILITIES,
        Permission.EDIT_ROUNDAVAILABILITIES,
        Permission.VIEW_DEBATE,
        Permission.VIEW_BALLOTSUBMISSIONS,
        Permission.EDIT_OLD_BALLOTSUBMISSIONS,
        Permission.ADD_BALLOTSUBMISSIONS,
        Permission.VIEW_NEW_BALLOTSUBMISSIONS,
        Permission.VIEW_RESULTS,
        Permission.VIEW_MOTION,
        Permission.VIEW_FEEDBACK, Permission.ADD_FEEDBACK,
        Permission.VIEW_CHECKIN,
        Permission.EDIT_PARTICIPANT_CHECKIN,
        Permission.VIEW_REGISTRATION,
    },
    'member': {  # legacy alias — same as editor
        Permission.VIEW_TEAMS, Permission.VIEW_ADJUDICATORS,
        Permission.VIEW_ROOMS, Permission.VIEW_INSTITUTIONS,
        Permission.VIEW_PARTICIPANTS,
        Permission.VIEW_ROUNDAVAILABILITIES,
        Permission.EDIT_ROUNDAVAILABILITIES,
        Permission.VIEW_DEBATE,
        Permission.VIEW_BALLOTSUBMISSIONS,
        Permission.EDIT_OLD_BALLOTSUBMISSIONS,
        Permission.ADD_BALLOTSUBMISSIONS,
        Permission.VIEW_NEW_BALLOTSUBMISSIONS,
        Permission.VIEW_RESULTS,
        Permission.VIEW_MOTION,
        Permission.VIEW_FEEDBACK, Permission.ADD_FEEDBACK,
        Permission.VIEW_CHECKIN,
        Permission.EDIT_PARTICIPANT_CHECKIN,
        Permission.VIEW_REGISTRATION,
    },
    'viewer': {
        Permission.VIEW_TEAMS, Permission.VIEW_ADJUDICATORS,
        Permission.VIEW_ROOMS, Permission.VIEW_INSTITUTIONS,
        Permission.VIEW_PARTICIPANTS,
        Permission.VIEW_ROUNDAVAILABILITIES,
        Permission.VIEW_DEBATE,
        Permission.VIEW_BALLOTSUBMISSIONS,
        Permission.VIEW_NEW_BALLOTSUBMISSIONS,
        Permission.VIEW_RESULTS,
        Permission.VIEW_MOTION,
        Permission.VIEW_FEEDBACK,
        Permission.VIEW_FEEDBACK_OVERVIEW,
        Permission.VIEW_BREAK, Permission.VIEW_BREAK_OVERVIEW,
        Permission.VIEW_CHECKIN,
        Permission.VIEW_REGISTRATION,
    },
}
