# Generated by Django 5.2.12 on 2026-04-03 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('tournaments', '0039_enforce_organization_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#7c3aed', help_text='Hex color code for the tag badge', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'participant tag',
                'verbose_name_plural': 'participant tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list, help_text="Filter by roles, e.g. ['debater', 'adjudicator']")),
                ('active_since', models.DateField(blank=True, help_text='Only include participants active since this date', null=True)),
                ('custom_emails', models.TextField(blank=True, help_text='Additional email addresses, one per line')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audience', to='campaigns.emailcampaign')),
                ('tournament_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
                ('tag_filter', models.ManyToManyField(blank=True, to='participant_crm.participanttag')),
            ],
            options={
                'verbose_name': 'campaign audience',
                'verbose_name_plural': 'campaign audiences',
            },
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('primary_role', models.CharField(choices=[('debater', 'Debater'), ('adjudicator', 'Adjudicator'), ('tab_director', 'Tab Director'), ('hybrid', 'Hybrid')], db_index=True, max_length=20)),
                ('total_rounds_debated', models.PositiveIntegerField(default=0)),
                ('total_rounds_adjudicated', models.PositiveIntegerField(default=0)),
                ('email_subscribed', models.BooleanField(db_index=True, default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_participants', to='tournaments.tournament')),
                ('tournaments_participated', models.ManyToManyField(blank=True, related_name='crm_participants', to='tournaments.tournament')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='participants', to='participant_crm.participanttag')),
            ],
            options={
                'verbose_name': 'participant profile',
                'verbose_name_plural': 'participant profiles',
                'ordering': ['-last_active'],
                'indexes': [models.Index(fields=['primary_role', 'email_subscribed'], name='participant_primary_2741e5_idx'), models.Index(fields=['primary_role', 'last_active'], name='participant_primary_318d4e_idx')],
            },
        ),
    ]
