# Generated by Django 5.2.7 on 2026-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_bulknotification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstatus',
            name='event',
            field=models.CharField(choices=[('processed', 'Processed'), ('dropped', 'Dropped'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('bounce', 'Bounced'), ('open', 'Opened'), ('click', 'Clicked'), ('unsubscribe', 'Unsubscribed'), ('spamreport', 'Marked as spam'), ('group_unsubscribe', 'Unsubscribed from group'), ('group_resubscribe', 'Resubscribed to group'), ('failed', 'Failed to send')], max_length=20, verbose_name='event'),
        ),
    ]
